data: >
  {
    "Oak": {
      "logs": [
        { "id": "LOG", "data": "0" },
        { "id": "LOG", "data": "4" },
        { "id": "LOG", "data": "8" },
        { "id": "LOG", "data": "12" }
      ],
      "leaves": [{ "id": "LEAVES", "data": "0" },{ "id": "LEAVES", "data": "8" }]
    },
    "Spruce": {
      "logs": [
        { "id": "LOG", "data": "1" },
        { "id": "LOG", "data": "5" },
        { "id": "LOG", "data": "9" },
        { "id": "LOG", "data": "13" }
      ],
      "leaves": [{ "id": "LEAVES", "data": "1" },{ "id": "LEAVES", "data": "9" }]
    },
    "Birch": {
      "logs": [
        { "id": "LOG", "data": "2" },
        { "id": "LOG", "data": "6" },
        { "id": "LOG", "data": "10" },
        { "id": "LOG", "data": "14" }
      ],
      "leaves": [{ "id": "LEAVES", "data": "2" },{ "id": "LEAVES", "data": "10" }]
    },
    "Jungle": {
      "logs": [
        { "id": "LOG", "data": "3" },
        { "id": "LOG", "data": "7" },
        { "id": "LOG", "data": "11" },
        { "id": "LOG", "data": "15" }
      ],
      "leaves": [{ "id": "LEAVES", "data": "3" },{ "id": "LEAVES", "data": "11" }]
    },
    "Acacia": {
      "logs": [
        { "id": "LOG_2", "data": "0" },
        { "id": "LOG", "data": "4" },
        { "id": "LOG", "data": "8" },
        { "id": "LOG", "data": "12" }
      ],
      "leaves": [{ "id": "LEAVES_2", "data": "0" },{ "id": "LEAVES_2", "data": "8" }]
    },
    "DarkOak": {
      "logs": [
        { "id": "LOG_2", "data": "1" },
        { "id": "LOG", "data": "5" },
        { "id": "LOG", "data": "89" },
        { "id": "LOG", "data": "13" }
      ],
      "leaves": [{ "id": "LEAVES_2", "data": "1" },{ "id": "LEAVES_2", "data": "9" }]
    }
  }